[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/paginas/index.html"
  status = 200

[[redirects]]
  from = "/Catalogo"
  to = "/paginas/Catalogo.html"
  status = 200

[[redirects]]
  from = "/autores"
  to = "/paginas/autores.html"
  status = 200

[[redirects]]
  from = "/contacto"
  to = "/paginas/contacto.html"
  status = 200

[[redirects]]
  from = "/genero"
  to = "/paginas/genero.html"
  status = 200

[[redirects]]
  from = "/libro"
  to = "/paginas/libro.html"
  status = 200

[[redirects]]
  from = "/pago-cancelado"
  to = "/paginas/pago-cancelado.html"
  status = 200

[[redirects]]
  from = "/pago-exitoso"
  to = "/paginas/pago-exitoso.html"
  status = 200

[[redirects]]
  from = "/privacidad"
  to = "/paginas/privacidad.html"
  status = 200

[[redirects]]
  from = "/producto"
  to = "/paginas/producto.html"
  status = 200

[[redirects]]
  from = "/revista"
  to = "/paginas/revista.html"
  status = 200

[[redirects]]
  from = "/sobre"
  to = "/paginas/sobre.html"
  status = 200
